language: android

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

jdk:
- oraclejdk8

env:
  global:
    - TERM=dumb
    - secure: ""
    - secure: ""


android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.1
  - android-23
  - extra
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-23

script: ./gradlew build

deploy:
  - provider: script
    script: scripts/bintrayUpload.sh
    skip_cleanup: true
    on:
      tags: true